name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install mkdocs material insiders
        run: pip install git+https://${{ secrets.GH_TOKEN }}@github.com/chazlarson/automaticSpoon.git

      - name: Build mkdocs
        run: mkdocs build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 86b9f680e99b6d172395cc7309a9d8a8
          projectName: docs
          directory: site
          gitHubToken: ${{ secrets.GH_TOKEN }}

      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

